### ISSUE TITLE
2d[Log]来相互认识一下吧~

### ISSUE THREAD

**Issue by evanchan92** [evanchan92/SocialPsychologyOverview#1]
模板：
* 名字
* 常出没地
* 如何结缘开智？
* 想在这次课程中获得什么？
* 最赞赏自己的是什么？

**Comment by evanchan92** [comment]
* 名字: 陈晨
* 常出没地：江苏南京
* 如何结缘开智？
    * 无意间发现阳老师博客，读了工作谈之后被震撼，一发不可收拾成为迷弟
* 想在这次课程中获得什么？
    * 上期没好好做作业...这期认真参与，积攒实操经验和内隐知识；
    * 通过教练的角色，帮助自己和更多同学成长；
* 最赞赏自己的一点是什么？

**Comment by dannuan** [comment]
* 名字：淡暖
* 常出没地：山西太原
* 如何结缘开智？
    * 爱贝睿——老阳——开智
* 想在这次课程中获得什么？
    * 找到一些问题的解
* 最赞赏自己的是什么？
    * 常换位思考
    * 在周围环境不好的时候不忘坚持自我

**Comment by auronzhong** [comment]
- 名字：钟慰/机器猫
- 常出没地：上海
- 如何结缘开智？
     - 在信息分析二期和开智结缘，无论是课上还是课下，都理性的让人沉迷，虽然懵懵懂懂，但享受这种醉氧体验。
- 想在这次课程中获得什么？
     - 上期划水，这期争取优秀
     - 内隐信息分析能力
     - 找到共同前进的同侪力量
- 最赞赏自己的是什么？
     - 相信「自我」的力量：我想要阅读，所以跨界了企业培训；我想要写作，所以每天一万写了200天；我想要健康，所以减掉了40斤。

**Comment by sebrina73** [comment]
- 名字：王喻珊
   - 常出没地：上海
   - 如何结缘开智？
        先入坑的爱贝睿，上了叨叨魏、陈忻的课，后来又上了高地清风的线下课，亲眼看到了开智派的真人，感觉很不一样
   - 想在这次课程中获得什么？
       根据ch2的自我定位，我是属于C类学员（平时信息搜索习惯比较差，主要靠度娘，上了课才开始学习的科学上网），所以本期我主要是走通一遍流程，以【完成基础作业、完成结业作业】为主要目的，对开智先有个感性的、全流程体验。第一稿作业屎一样的也没关系，先完成，再完美。在此也是感谢陈晨教练对我屎一样作业的鼓励，这也是我选择想要参与这个团队的原因之一。
   - 最赞赏自己的是什么？
        嚣张！
        虽然自己在开智里面是妥妥的学渣，面对这么多优秀的大家心里很有压力，交的作业也很烂，但还是很嚣张的敢于在群里提出小白问题（ch1时那个下载不了zotero后来被阳老翻牌子提炼示范了高阶模型的就是我）、深夜12:30很嚣张的骚扰陈晨教练要求抱大腿带我做作业、以及此时此刻我其实ch3卡包都还没有刷完但还是很嚣张的先在这里写issue1……诸如此类，厚着脸皮坚持做自己喜欢的事，不怕被你们嘲笑，因为我明白内在动机的重要性嘿嘿嘿

**Comment by Miffyhong** [comment]
**名字:** 
洪菲 （轻轻的菲）
**常出没地：**
北京/天津/宁夏银川/
**如何结缘开智？**
朋友介绍认识到阳老师，参加了几次开智的活动很喜欢开智的风格，尤其是写作风格~很希望自己也可以写出优美的文字。
**想在这次课程中获得什么？**
想在这次信息分析课程中掌握全部的信息分析方法，并且在短时间内不断内化和应用。另外，最近自己也在研究心理学相关的东西，得到上面的武志红专栏看了很多遍，不断三省吾身，也很希望能够把这些东西应用在实际生活中。
**最赞赏自己的是什么？**
最赞赏...随时随地都有让自己和身边人开心的能力哈哈哈。我自认为是一个很幸运的人，希望认识我的人都能因此快乐哈哈。

**Comment by sherazhang** [comment]
名字:张丹（shera）
常出没地：深圳
如何结缘开智：2016年，通过一个朋友路意，知道阳老师，从此再也没有出圈，一直到现在。
想在这次课程中获得什么：将信息分析课的知识点内化。希望打破自我封闭，与人一起协同成长。
最赞赏自己的是什么：追求自己真正想要的东西的勇气。
