### ISSUE TITLE
9d[Discuss]项目大方向思考

### ISSUE THREAD

**Issue by evanchan92** [evanchan92/SocialPsychologyOverview#2]
请大家在这个issue中给出自己对于项目整体方向的思考，建议模板如下：

### 1. 项目目标具体定多大？
不断提醒我们自己，要约束野心，但是要足够有趣足够有信息量。

**Comment by evanchan92** [comment]
先来谈我的想法，抛砖引玉：
### 项目目标：
#### 1. 项目研究范围：
1. 对社会心理学的时、空、变量分析；
2. 学科大牛及其里程碑式贡献；
3. 当前领域内前沿话题； 
4. 社会心理学的应用场景；
5. 如何反向利用社会心理学来促成社会改变（选做）


#### 2. 项目呈现：
1. 完整信息分析报告；
2. 路演ppt；
3. 参加路演。

### 项目拆解思路及解决办法：
1. 对社会心理学的时、空、变量分析；
    * 时间：领域里程碑事件
        * 维基百科
        * 通识读物
        * 专业教材
        * 大牛访谈
    * 空间：领域重要分支和主要讨论范围
        * 知识图谱
        * 通识读物
2. 学科大牛及其里程碑式贡献
    * 谷歌学术 H-index；
    * 主流杂质编委；
    * 国家级学术组织核心成员；
    * 
3. 当前学术前沿话题：
4. 社会心理学的应用场景；
5. 如何反向利用社会心理学来促成社会改变（选做）

**Comment by sebrina73** [comment]
先交第一稿，想到再优化：
1、目标
     我看了一下我们团队的成员，基本是各行各业的在职人士，行业之间没有重叠的，但是估计大家大概率都有想要改变他人的需求，不然也不会选这个作为结业题目了吧？所以就5.《如何反向利用社会心理学来促成社会改变（选做）》这个话题，我很感兴趣。
2、拆解
     接上，就这个话题，我想细分为两块：
    1）如何促进他人改变，大家提炼出共性的部分（注：这个结合行为科学家《如何想到又做到》一书其实也有现成的SCIENCE模型可以参考）
    2）大家结合自身所在的职业，选取各自眼下想要解决的组织性、战略性问题，如何改变单位领导们、同事们的行为，结合实际案例，提出个性化的部分。如我现在要推保险AI项目，这是个前沿项目，但是同事们里面很多老弱病残封闭不思进取的人，我如何利用社会心理学促成公司战略达成？
changelog
20181230 v1.0初稿

**Comment by auronzhong** [comment]
发现一个有趣的知识，社会心理学并不仅是谈社会问题的。

阳老师在发布课题的时候，描述是：我心、他心、天下心。

我比照了《社会心理学》，对应的是 社会思维、社会影响、社会关系 三个主题。

![](http://zhwbitcron.oss-cn-beijing.aliyuncs.com/bitcron/2018-12-30-031913.jpg)

![](http://zhwbitcron.oss-cn-beijing.aliyuncs.com/bitcron/2018-12-30-031933.jpg)

**Comment by Miffyhong** [comment]
先简单抛下自己的一点儿思路，我觉得社会心理学有几个可以入手的点

- 人性。大多数工种离不开对人性的研究和琢磨，而社会心理学把个人放在一个社会集体意识和群格之下，那么从小处来说我们是否能够针对某一类型的群体为切入点和抓手进行社会心理学的研究。

- 查找和研究社会心理学领域的大牛，提炼他们的思维模型，看看大牛的哪些习惯和生活方式、思维方式能够让大牛成长为大牛，（特定社会心理学领域）

- 社会心理学的整体发展脉络，从宏达的历史观点来看待社会心理学的变迁和发展。

当然以上观点也可以在本次大作业中全部包含进去~

over

**Comment by evanchan92** [comment]
增补信息：
### 空间线索：
来源：《牛津通识读本》——生活中的心理学
内容摘要：

### 1.社会助长现象：

他人在场通常会影响我们的行为：有些事你一人在家可能会做，但在公众场合你绝对不会做。其中一个明显形式就是竞争。如果人们相信他们是在和某人竞争——即使没有奖，他们的表现也会更好。看来关键因素是他人在场，而不会竞争的氛围。即使在要求人们不要竞争的情况下，若看到别人在工作（**工作效应**）或别人在看自己工作（**观众效应**），人们工作的速度就会加快一些。

---
### 2.对领导风格的研究：

**2.1 领导的环境因素：**如果条件不是最好也不是最坏，注重协调关系的领导就对群体比较有益；而当群体条件较为极端时，爱发号施令的、爱控制的、注重分派任务的领导反而能较受欢迎。例如希特勒在德国一战后崛起。

**2.2 领导风格能够影响群体成员的行为和生产率：**
    ①一般来说，民主的风格会通过群体成员之间良好的人际关系来提高生产率，
    ②独裁的风格更加专制、具有指令性，它使得群体成员没有决策权，虽然说生产率差不多（条件是领袖在场），但是会使得群体成员之间人际关系较差，合作较少。
    ③放任自流的领导让群体各行其是，结果，其生产率比民主的或者独裁的领导取向下都要低。

**2.3 领导人物的塑造**：有些研究人员随便挑选了一个人放到中心位置上，实验表明，如果群体成员被迫只同一个中心人物沟通，那么这个人就开始发挥领袖的作用了。和占据外围位置的人相比，中心位置的人发出的信息更多，解决问题更快、犯的错误更少，对他们本人和群体的努力也更为满意。

---
### 3.从众：
处在群体之中，而自己的意见与大多数人的不同，在这种情况下，你可能会改变自己的观点去服从群体——尤其是你对自己观点没把握的时候，或你有理由相信大多数人有更可靠的消息来源时。然而，当你确认你是正确的，而群体不是正确的时候，你会屈服于群体的压力而顺从么？
感受到来自个人或群体的压力而改变自己的行为或态度，叫做**从众**。

### 4. 服从：
经典实验：米尔格拉姆的电击实验   => [Link](https://wiki.mbalib.com/wiki/%E7%B1%B3%E5%B0%94%E6%A0%BC%E6%8B%89%E5%A7%86%E7%9A%84%E6%9C%8D%E4%BB%8E%E8%AF%95%E9%AA%8C)

### 5. 偏见：
经典实验：[蓝眼珠好还是棕眼珠好](https://www.ettoday.net/dalemon/post/32477)

**Comment by dannuan** [comment]
### 关于cite space
要用wos搜索一些领域关键字，具体有哪些大家可以一起来补充

**Comment by sherazhang** [comment]
### 社会心理学的全局认识首先要回答这四个问题：
* 知识源头
  * 学科的核心知识体系，它的源头是从哪来的？它最早是解决什么样的问题而诞生？有什么样的东西在支撑它这一门学科的成立？
* 核心话语体系
 * 自己的一套跟其他学科不一样的话语体系。
* 二级推演体系
 * 这个话语体系会延伸到下一个层面，推演出二级话语体系。
*其他学科它是怎么看待这个学科的大问题。

在回答这四个问题的过程中，就会有出现大牛，领域，里程碑事件，知识图谱，核心期刊等等内容。

### 如果想要作业有亮点，可以从应用价值入手，比如从常识和反常识角度入手：
>1、常识；：掌握大众关于整个学科的共识。比如，不知道认知偏差。
2、反常识；发现整个学科与大众观念不一样的。比如，知道了卡尼曼。
3、反常识的反常识；构建整个学科的脉络，比如，知道了卡尼曼，更知道了纪仁泽这些与卡尼曼对着干的。
4、常识。在这些基础上，又构建了一个正确的常识，没那么偏颇。

通过这些一些角度总结社会心理学，如何成为我们的秘密武器！



----------------------------对任意一个领域全局认识的套路-----------------------------------------
主题学习是快速进入任意一个领域的最好办法。如果将上述方法推广到学习任意一个学科，就是快速学习任意一个学科的「最小知识法则」。学习任意一个学科，你都问自己三个问题：
### 知识的源头

源头落花每流出，亦有波澜。第一个问题就是这一个学科的核心知识体系，它的源头是从哪来的？以认知语言学举例，认知语言学它最早是解决什么样的问题而诞生？认知语言学它是因为什么样的背景诞生的，
有什么样的东西在支撑它这一门学科的成立？因此，此时大家不要去看它现在的教材，而是要看它最原始的那一本著作。认知语言学是莱考夫1980年写的那一本《我们赖以生存的隐喻》。读后，我们大体会明白认知语言学是因为「范畴与范畴化」而诞生。

### 核心话语体系

第二个问题咱们要明白，某个学科它因为某个原因诞生了，那么它必然是有自己的一套跟其他学科不一样的话语体系。比如认知语言学，它跟「认知修辞学」与「认知心理学」就是不一样的思路。那么它的侧重点是什么？仍以认知语言学为例，我们大体会明白，它关心「基本层次隐喻」作为人类的基本思维方式。

### 二级推演体系

任何一个学科，只要它产生了一个只属于该学科的特殊话语体系，那么，这个话语体系会延伸到下一个层面，推演出二级话语体系。咱们就要明白认知语言学的这个二级结论是什么。这就是「象似性原则」与「经济原则」相互冲突，导致人类心智与语言的一些有趣之处。比如我们的语言习惯一定是有生命的大于没有生命的；人类先于动物；阳性大于阴性。比如咱们只会说美女与野兽，而不会说野兽与美女；只会说夫唱妇随、男耕女织，而不会说女耕男织。
这就是学习任何一个学科要掌握的三个最小知识。我将其称之为学习任意一个学科的「最小知识原则」。如果你掌握了某个学科的三个最小知识，你就容易理解该学科的全局，不至于被它枝节带歪路。但是，功夫在诗外，任意一个学科都存在「知识的诅咒」。此时，我们需要跳到掌握任何一个学科的第四个问题：

### 其他学科它是怎么看待这个学科的大问题。
仍然以认知语言学举例，此时，我们就关心的是社会心理学如何看隐喻，这就是社会心理学的「自我归类论」与「社会认同论」解决的问题。

**Comment by evanchan92** [comment]
### 知识源头
* 学科的核心知识体系，它的源头是从哪来的？
* 它最早是解决什么样的问题而诞生？
* 有什么样的东西在支撑它这一门学科的成立？
=》这个话题其实包含在了我们对时间线索的探索之中，但确实这一点需要特别明确

### 核心话语体系
* 自己的一套跟其他学科不一样的话语体系。
* 二级推演体系：这个话语体系会延伸到下一个层面，推演出二级话语体系。
=》 空间范畴内会讨论这个问题，社会心理学主要研讨哪些范围

### 其他学科它是怎么看待这个学科的大问题：
=》 行为经济学?
=》 社会学？
=》 认知科学？

**Comment by sherazhang** [comment]
@evanchan92   是的，
在回答这四个问题的过程中，就会有出现大牛，领域，里程碑事件，知识图谱，核心期刊等等内容。
在梳理完知识，去呈现的时候，可以用时间/空间/变量的维度去呈现。

我们要解决的是四个问题，“时间/空格/变量“或者”大牛，知识图谱“等等，都是为了了回答问题的手段。
我想强调的是这个。

我看了你些的目标，在信息收集方面很全。不过我作为昨天没参加会议的人，其实并不知道你们收集了信息之后想干嘛。所以我将这4个问题重点提出来，作为我们需要关注的点。也方便其他没有参加昨天参加会议的人，能快速了解项目要回答的问题是什么，而不是项目要搜集的资料是什么。
